"""pack size, blister size, product title

Revision ID: acc2627e12bb
Revises: b61d12e62198
Create Date: 2026-09-26 15:15:45.811983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc2627e12bb'
down_revision: Union[str, Sequence[str], None] = 'b61d12e62198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blister_size', sa.Integer(), nullable=True))

    with op.batch_alter_table('product_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pack_size', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('blister_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_codes', schema=None) as batch_op:
        batch_op.drop_column('blister_size')
        batch_op.drop_column('pack_size')
        batch_op.drop_column('unit')
        batch_op.drop_column('title')

    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_column('blister_size')

    # ### end Alembic commands ###
