"""initial schema

Revision ID: b61d12e62198
Revises: 
Create Date: 2026-09-26 11:40:07.696135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b61d12e62198'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('invite_code', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_families_invite_code'), ['invite_code'], unique=True)

    op.create_table('product_codes',
    sa.Column('gtin', sa.String(length=14), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('form', sa.String(length=60), nullable=True),
    sa.Column('dosage', sa.String(length=60), nullable=True),
    sa.Column('active_ingredient', sa.String(length=200), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('gtin')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_family_id'), ['family_id'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'user_id')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('form', sa.String(length=60), nullable=True),
    sa.Column('dosage', sa.String(length=60), nullable=True),
    sa.Column('active_ingredient', sa.String(length=200), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('indications', sa.Text(), nullable=False),
    sa.Column('contraindications', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('min_quantity', sa.Float(), nullable=True),
    sa.Column('gtin', sa.String(length=14), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicines_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicines_gtin'), ['gtin'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicines_name'), ['name'], unique=False)

    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('opened_at', sa.Date(), nullable=True),
    sa.Column('serial', sa.String(length=64), nullable=True),
    sa.Column('batch', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_medicine_id'), ['medicine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_serial'), ['serial'], unique=False)

    op.create_table('user_marks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('helps_me', sa.Boolean(), nullable=False),
    sa.Column('personal_note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'medicine_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_marks')
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_serial'))
        batch_op.drop_index(batch_op.f('ix_packages_medicine_id'))

    op.drop_table('packages')
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicines_name'))
        batch_op.drop_index(batch_op.f('ix_medicines_gtin'))
        batch_op.drop_index(batch_op.f('ix_medicines_family_id'))

    op.drop_table('medicines')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_family_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_family_id'))

    op.drop_table('categories')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('product_codes')
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_families_invite_code'))

    op.drop_table('families')
    # ### end Alembic commands ###
